### ISSUE TITLE
Throwable.addSuppressed is missing

### ISSUE THREAD

**Issue by jonnyzzz** [Kotlin/kotlinx.support#1]
I have the following code 

```
fun Throwable.addSuppressed(t : Throwable) {
  (this as java.lang.Throwable).addSuppressed(t)
}
```

**Comment by ilya-g** [comment]
Here it is: https://github.com/Kotlin/kotlinx.support/blob/master/kotlinx-support-jdk7/src/main/kotlin/Exceptions.kt#L8
