### ISSUE TITLE
AutoCloseable.use must be implemented using try-finally

### ISSUE THREAD

**Issue by vbezhenar** [Kotlin/kotlinx.support#3]
Example to reproduce:

```
import kotlinx.support.jdk7.use

fun main(args: Array<String>) {
  MyAutoCloseable().use {
    return
  }
}

class MyAutoCloseable : AutoCloseable {
  override fun close() {
    println("AutoCloseable.close")
  }
}
```

This example doesn't call `close()`. Standard library's `Closeable.use` correctly closes resource even with return.

**Comment by ilya-g** [comment]
Fixed it in a branch, you can take a look at the commit above.
Will merge to the master today.
