### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by dazraf** [Kotlin/kotlinx.support#6]
Hello,
Great library. Really needs to be on maven central. Most corporate networks do not allow access to other repos. Thanks :-)

**Comment by ilya-g** [comment]
Hi,
as soon as Kotlin 1.1 is released (to maven central) the need in this library will greatly decrease.

**Comment by dazraf** [comment]
Yes but our third party libraries (Corda) depends on this. 

Surely deploying to maven isn't such a huge deal?

**Comment by ilya-g** [comment]
Closing as obsolete.
