### ISSUE TITLE
Is this project deprecated by JDK artifacts of the stdlib?

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.support#7]

**Comment by Bluexin** [comment]
https://github.com/Kotlin/kotlinx.support#kotlinxsupport
```
In Kotlin 1.1+ please use the standard library artifacts instead: kotlin-stdlib-jre7 and kotlin-stdlib-jre8.```

**Comment by ilya-g** [comment]
> Is this project deprecated by JDK artifacts of the stdlib?

Yes. One should use `kotlin-stdlib-jdk7`/`kotlin-stdlib-jdk8` artifacts instead.
